print("Μήπως ξέρεις γιατί οι ελέφαντες βάφουν τα νύχια τους κόκκινα ?")
input()
print("Για να κρύβονται πίσω απο τίς παπαρούνες.")
print()
print("Έχεις δεί ελέφαντα να κρύβεται πίσω απο παπαρούνα ?")
input()
print("Είδες τί καλά πού κρύβεται ?")
print()
print("Ένα ακόμα. Τόκ-τόκ")
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
